name: on_hand
description: An open source browser extension to save your favorite bookmarks on a "new tab" page.
publish_to: 'none'
version: 1.1.1+1

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  html: ^0.15.0
  image: ^3.2.0
  validators: ^3.0.0
  json_theme: ^4.0.0+6
  easy_localization: ^3.0.1
  cupertino_icons: ^1.0.2
  reorderables: ^0.5.0
  flutter_speed_dial: ^6.0.0
  enough_convert: ^1.6.0
  file_saver: ^0.1.0
  flutter_dropzone: ^3.0.5
  dotted_border: ^2.0.0+2
  device_info_plus: ^4.0.0
  file_picker: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - themes/
    - translations/