name: on_hand
description: An open source browser extension to save your favorite bookmarks on a "new tab" page.
publish_to: 'none'
version: 2.0.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  html: ^0.15.5
  validators: ^3.0.0
  easy_localization: ^3.0.7
  enough_convert: ^1.6.0
  flutter_dropzone: ^4.2.0
  dotted_border: ^2.1.0
  device_info_plus: ^11.1.1
  file_picker: ^8.1.4
  jovial_svg: ^1.1.23
  reorderable_grid_view: ^2.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - translations/
