name: on_hand
description: An open source browser extension to save your favorite bookmarks on a "new tab" page.
publish_to: 'none'
version: 2.0.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  html: ^0.15.4
  validators: ^3.0.0
  easy_localization: ^3.0.3
  enough_convert: ^1.6.0
  flutter_dropzone: ^3.0.6
  dotted_border: ^2.1.0
  device_info_plus: ^9.1.1
  file_picker: ^6.1.1
  jovial_svg: ^1.1.20
  reorderable_grid_view: ^2.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - translations/
